package com.zone.tasksphere.dto.response;

import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Builder;
import lombok.Data;

import java.time.Instant;

@Data
@Builder
@Schema(description = "AI or fallback analysis for a report")
public class ReportInsightResponse {

    @Schema(description = "Report type", example = "BURNDOWN")
    private String reportType;

    @Schema(description = "Display title", example = "AI analysis")
    private String title;

    @Schema(description = "Narrative insight content")
    private String analysis;

    @Schema(description = "Whether the text was generated by the AI model")
    private boolean aiGenerated;

    @Schema(description = "Model name when AI generation succeeds")
    private String model;

    @Schema(description = "Generation timestamp")
    private Instant generatedAt;
}
